archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: main.go
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  sort: asc
checksum:
  name_template: "checksums.txt"
project_name: storydb
snapshot:
  name_template: "{{ incpatch .Version }}-next"
